on:
  push:
    branches:
     - master

jobs:
  build-preview:
    runs-on: ubuntu-latest
    permissions:
      # REQUIRED: Allow updating fingerprint in action caches
      actions: write
      # Following permissions are required for private repos
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: 🏗  Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
    
      - name: Install dependencies
        run: npm install
    
      - name: Create preview builds if needed
        uses: expo/expo-github-action/preview-build@main
        with:
          command: eas build --profile preview --platform android --verbose

      - name: List files
        run: ls -l ./
        
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: expo-artifacts
          path: '**/*.apk'  # Adjust the path to match the location of your APKs
          
